[package]
name = "hn_api"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"
